# Generated by Django 2.2.16 on 2020-12-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['id'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
    ]
